# Generated by Django 4.2.13 on 2024-07-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='id',
            new_name='p_id',
        ),
        migrations.RenameModel(
            old_name='name',
            new_name='p_name',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RenameField(
            model_name='p_id',
            old_name='id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='p_name',
            old_name='name',
            new_name='p_name',
        ),
    ]
