# Generated by Django 4.2.13 on 2024-07-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0002_p_contact_rename_id_p_id_rename_name_p_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
